### ISSUE TITLE
Conflicted version with System.Reactive

### ISSUE THREAD

**Issue by throwaway122333** [xamarin/mqtt#180]
Hi

I can't use System.MQTT with xamarin.ios and i get this error:
> Can't resolve the reference 'System.Reactive.Subjects.SubjectBase`1', referenced from the method 'System.Void System.Net.Mqtt.Sdk.ClientPacketListener/<DispatchPacketAsync>d__23::MoveNext()' in 'System.Reactive.Linq, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.	project C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	804	

I used the same code on Xamarin.Android and it works, but nothing with the ios version

**Comment by ibebbs** [comment]
Hah... was just about to report exactly this error.

I'm using System.Net.Mqtt v0.6.0-beta in two projects currently; [Cmqtt](https://github.com/ibebbs/Cmqtt) and [PowerFull](https://github.com/ibebbs/PowerFull). While the former works perfectly, the latter encounters the following error due to already having a dependency on System.Reactive v4.1.6:

```
FileNotFoundException: Could not load file or assembly 'System.Reactive.Linq, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.
```

I have tried adding assembly binding redirects to the application but to no avail (there is conflicting information as to whether these are even still respected in modern .net core apps).

I forked this repository and upgraded System.Reactive to v4.1.6 which builds and passes all tests without any other change. Running PowerFull using this locally built System.Net.Mqtt assembly doesn't produce the above exception.

I would be happy to prepare a PR if this is something you're keen on accepting.
